#!/usr/bin/env python3
"""Freeze the input-independent 3B FP32-B RoPE cache for native builds."""
import argparse
import hashlib
import json
from pathlib import Path
import torch

p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
a.output.mkdir(parents=True,exist_ok=False);torch.set_num_threads(4)
if torch.__version__!='2.9.0+cpu':raise RuntimeError('Use the locked FP32-B reference environment')
freq=1./(10000.**(torch.arange(0,42,2).float()/42.))
angle=torch.arange(1024,dtype=torch.float32)[:,None]*freq[None,:]
phase=torch.stack([angle.cos(),angle.sin()],-1)
parts=['// Generated by tools/generate_rope_table.py from the locked FP32-B arithmetic.\n#pragma once\n#include <bit>\n#include <cstdint>\nnamespace seedvr2::engine::rope_fp32 {\n']
for name,t in [('frequencies',freq),('cos_sin',phase)]:
    words=t.contiguous().numpy().view('uint32').reshape(-1)
    parts.append(f'inline constexpr std::uint32_t {name}[] = {{\n')
    parts.extend(','.join(f'0x{int(x):08x}u' for x in words[i:i+8])+',\n' for i in range(0,len(words),8));parts.append('};\n')
parts.append('inline float frequency(int pair) { return std::bit_cast<float>(frequencies[pair]); }\ninline float phase(int position, int pair, int sine) { return std::bit_cast<float>(cos_sin[(position*21+pair)*2+sine]); }\n}\n')
out=a.output/'rope_fp32_table.hpp';out.write_text(''.join(parts))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
report=dict(schema_version='seedvr2-rope-cache-v1',torch_version=torch.__version__,cpu_capability=torch.backends.cpu.get_cpu_capability(),scope='Fixed mathematical positional constants only; no user inputs, activations, or learned weights',positions=1024,pairs=21,formula='freq=1/(10000**(float32(arange(0,42,2))/42)); angle=float32(position)*freq; float32 CPU cos/sin',generator_sha256=sha(Path(__file__)),header_sha256=sha(out),table_bytes=phase.numel()*4,model_verified=False)
(a.output/'provenance.json').write_text(json.dumps(report,indent=2)+'\n')
