
  windows-experimental:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v5
        with:
          path: "VulkanSDK"
          key: vulkansdk-windows-1.3.290.0
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.290.0/windows/VulkanSDK-1.3.290.0-Installer.exe?Human=true" -OutFile VulkanSDK-Installer.exe
          7z x -aoa ./VulkanSDK-Installer.exe -oVulkanSDK
      - name: deps
        shell: pwsh
        run: |
          $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"
          vcpkg install openssl sqlite3 libjpeg-turbo ffmpeg
          choco install -y pkgconfiglite
      - name: cli11
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://codeload.github.com/CLIUtils/CLI11/tar.gz/cbd58a3696887b34c70949aef21a71735a0c2ad5" -OutFile cli11.tar.gz
          mkdir .deps\install
          tar -xzf cli11.tar.gz
          cd CLI11-cbd58a3696887b34c70949aef21a71735a0c2ad5
          cmake -B build -DCMAKE_INSTALL_PREFIX=..\.deps\install
          cmake --install build
      - name: configure
        shell: pwsh
        run: |
          $env:VULKAN_SDK = "$(pwd)/VulkanSDK"
          $env:PKG_CONFIG_PATH = "$(pwd)/vcpkg_installed/x64-windows/lib/pkgconfig;$(pwd)/vcpkg_installed/x64-windows/share"
          $env:CMAKE_POLICY_VERSION_MINIMUM = "3.5"
          mkdir build; cd build
          cmake -A x64 -DSEEDVR2_BUILD_WEB=OFF -DCMAKE_PREFIX_PATH="$(pwd)/../.deps/install" ../src
      - name: build
        shell: pwsh
        run: |
          cd build
          cmake --build . --config Release -j 2
          ./Release/seedvr2.exe version
